[package]
name = "lanis-rs"
version = "0.1.0"
authors = ["Rajala1404"]
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["json", "cookies"] }
reqwest_cookie_store = "0.8.0"
tokio = {version = "1.40.0", features = ["rt-multi-thread", "macros"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
scraper = "0.20.0"
rsa = "0.10.0-pre.3"
rand = "0.8.5"
base64 = "0.22.1"