[package]
name = "lanis-rs"
version = "0.1.0"
authors = ["Rajala1404"]
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
tokio = {version = "1.40.0", features = ["full"]}
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"