[package]
name = "lanis-rs"
version = "0.1.0"
authors = ["Rajala1404"]
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "cookies"] }
reqwest_cookie_store = "0.8.0"
tokio = {version = "1.40.0", features = ["full"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"